name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  modularpipeline:
    strategy: 
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x 

      - name: Run .NET
        run: dotnet run -c Release --hangdump --hangdump-filename hangdump.tests.dmp --hangdump-timeout 10s
        working-directory: TestPlatformRepro
        
      - name: Upload Hang Dumps
        uses: actions/upload-artifact@v4.6.1
        if: always()
        with:
          name: HangDump${{matrix.os}}
          path: '**/hangdump*'
